.PHONY:=clean all 

TARGET:=ls.exe
SOURCE_FILES:=main.c

CC:=gcc

CFLAGS:=
LD_FLAGS:=
HEADER_PATH:=
LIB_PATH:=

$(TARGET): $(SOURCE_FILES)
	$(CC) $(HEADER_PATH) $(CFLAGS) $< $(LIB_PATH) $(LD_FLAGS) -o $@